"""create sessions rounds responses

Revision ID: 159477864adc
Revises: 
Create Date: 2026-09-27 18:29:23.168700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '159477864adc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_name', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='session_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_ended_at'), 'sessions', ['ended_at'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Enum('PENDING', 'CORRECT', 'WRONG', 'ABANDONED', name='round_result'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_rounds_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('session_id', 'round_number', name=op.f('uq_rounds_session_id_round_number'))
    )
    op.create_table('responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_responses_round_id_rounds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responses')),
    sa.UniqueConstraint('round_id', name=op.f('uq_responses_round_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_ended_at'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
    sa.Enum(name='round_result').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='session_status').drop(op.get_bind(), checkfirst=True)
